package com.openai.controller;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.stream.Collectors;

import static org.springframework.ai.chat.memory.ChatMemory.CONVERSATION_ID;

@RestController
@RequestMapping("/api/rag")
public class RAGController {
    private final ChatClient chatClient;
    private final VectorStore vectorStore;
    // invoke the web search chat client
    private final ChatClient webSearchRAGChatClient;

    public RAGController(@Qualifier("chatMemoryChatClient") ChatClient chatClient, VectorStore vectorStore, @Qualifier("webSearchRAGChatClient") ChatClient webSearchRAGChatClient) {
        this.chatClient = chatClient;
        this.vectorStore = vectorStore;
        this.webSearchRAGChatClient = webSearchRAGChatClient;
    }

    /*@Value("classpath:/promptTemplates/systemPromptRandomDataTemplate.st")
    Resource systemPromptRandomDataTemplate;

    @Value("classpath:/promptTemplates/systemPromptTemplate.st")
    Resource systemPromptTemplate;*/


    @GetMapping("/random/chat")
    public ResponseEntity<String> randomChat(@RequestHeader("username") String username, @RequestParam("message") String message) {
        // we can achieve this by configuring RetrievalAugmentationAdvisor
        /*SearchRequest searchRequest = SearchRequest.builder().query(message).topK(3).similarityThreshold(0.5).build();
        List<Document> similarDocs = vectorStore.similaritySearch(searchRequest);
        String similarContext = similarDocs.stream()
                .map(Document::getText)
                .collect(Collectors.joining(System.lineSeparator()));*/
        String answer = chatClient.prompt()
                // system related prompt will be generated by chat client in config file
                /*.system(
                        promptSystemSpec -> promptSystemSpec.text(systemPromptRandomDataTemplate).param("documents", similarContext)
                )*/
                .advisors(a -> a.param(CONVERSATION_ID, username))
                .user(message)
                .call()
                .content();
        return ResponseEntity.ok(answer);
    }

    @GetMapping("/document/chat")
    public ResponseEntity<String> documentChat(@RequestHeader("username") String username, @RequestParam("message") String message) {
        // we can achieve this by configuring RetrievalAugmentationAdvisor
        /*SearchRequest searchRequest = SearchRequest.builder().query(message).topK(3).similarityThreshold(0.5).build();
        List<Document> similarDocs = vectorStore.similaritySearch(searchRequest);
        String similarContext = similarDocs.stream()
                .map(Document::getText)
                .collect(Collectors.joining(System.lineSeparator()));*/
        String answer = chatClient.prompt()
                // system related prompt will be generated by chat client in config file
                /*.system(
                        promptSystemSpec -> promptSystemSpec.text(systemPromptTemplate).param("documents", similarContext)
                )*/
                .advisors(a -> a.param(CONVERSATION_ID, username))
                .user(message)
                .call()
                .content();
        return ResponseEntity.ok(answer);
    }

    // api to use tavily for web search rag workflow
    @GetMapping("/web-search/chat")
    public ResponseEntity<String> webSearchChat(@RequestHeader("username") String username, @RequestParam("message") String message) {
        String answer = webSearchRAGChatClient.prompt()
                .advisors(a -> a.param(CONVERSATION_ID, username))
                .user(message)
                .call()
                .content();
        return ResponseEntity.ok(answer);
    }
}
